name: Build-Installers

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master ]

jobs:
  # linux:
  #   name: "Linux"
  #   runs-on: ubuntu-18.04
  #   steps:
  #   - uses: actions/checkout@v2
  #     with:
  #       fetch-depth: 0 # Indicate full history so Nerdbank.GitVersioning works.

  #   - name: Setup .NET Core
  #     uses: actions/setup-dotnet@v1
  #     with:
  #       dotnet-version: 3.1.302

  #   - name: Install dependencies
  #     run: dotnet restore --force

  #   - name: Build Linux Payloads
  #     run: dotnet build -c Release src/linux/Packaging.Linux/Packaging.Linux.csproj

  #   - name: Upload Installers
  #     uses: actions/upload-artifact@v2
  #     with:
  #       name: LinuxInstallers
  #       path: |
  #         out/linux/Packaging.Linux/deb/Release/*.deb
  #         out/linux/Packaging.Linux/tar/Release/*.tar.gz

  linux_publish:
    name: 'Publish Linux'
    runs-on: windows-latest
    # needs: linux
    steps:
    # - name: 'Download Installers'
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: LinuxInstallers
    - uses: actions/checkout@v2

    # - name: Install ESRP Client
    #   shell: pwsh
    #   env:
    #     AZDEV_PAT: ${{ secrets.MICROSOFT_AZDEV_NUGET_PAT }}
    #     NUGET_FEED: "https://microsoft.pkgs.visualstudio.com/_packaging/ESRP/nuget/v3/index.json"
    #   run: |
    #     echo "Using nuget feed $env:NUGET_FEED"
    #     nuget.exe sources add -name esrp -source "$env:NUGET_FEED" -username FOOBAR -password "$env:AZDEV_PAT"
    #     nuget.exe install Microsoft.EsrpClient -source "$env:NUGET_FEED" -OutputDirectory ./esrp

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install ESRP Key
      env:
        ESRP_PRIVATE_KEY: ${{ secrets.ESRP_PRIVATE_KEY }}
        ESRP_PRIVATE_KEY_PASSWORD: ${{ secrets.ESRP_PRIVATE_KEY_PASSWORD }}
        ESRP_PRIVATE_KEY_MD5: ${{ secrets.ESRP_PRIVATE_KEY_MD5 }}
      run: |
        python .github\workflows\install_esrp_key.py ESRP_PRIVATE_KEY ESRP_PRIVATE_KEY_PASSWORD ESRP_PRIVATE_KEY_MD5